window.DUST_COURSES = [
  {id:'c01',track:'common',phase:1,title:'认识 DUST 与工程安全',duration:'45 MIN',level:'入门',tags:['安全','规范'],summary:'了解战队协作方式、实验室安全边界与机器人调试红线。',goals:['理解战队项目周期与角色分工','掌握上电、急停与电池安全规范','完成安全知识检查'],tasks:['阅读实验室安全手册','完成上电前检查清单','通过 10 题安全测验'],deliverable:'一份个人安全检查清单'},
  {id:'c02',track:'common',phase:1,title:'Git 与团队协作',duration:'90 MIN',level:'入门',tags:['Git','协作'],summary:'从分支、提交到评审，建立可追溯的工程协作习惯。',goals:['掌握分支与提交规范','理解 Pull Request 工作流','学会处理基础冲突'],tasks:['创建训练分支','提交规范化 Commit','发起并完成一次代码评审'],deliverable:'一个通过评审的 Pull Request'},
  {id:'c03',track:'common',phase:1,title:'Linux 与开发环境',duration:'120 MIN',level:'入门',tags:['Linux','CLI'],summary:'掌握机器人开发常用命令、权限、进程和环境配置。',goals:['熟悉文件与权限操作','掌握进程和日志排查','搭建可复现开发环境'],tasks:['完成命令行闯关','定位一个模拟进程故障','编写环境配置说明'],deliverable:'可复现的开发环境文档'},
  {id:'c04',track:'common',phase:1,title:'C / C++ 工程基础',duration:'3 HOURS',level:'基础',tags:['C++','代码质量'],summary:'聚焦机器人项目所需的内存、接口、编译与调试能力。',goals:['理解栈、堆与生命周期','使用 CMake 组织工程','用调试器定位错误'],tasks:['实现环形缓冲区','接入单元测试','修复内存错误'],deliverable:'带测试的基础组件'},
  {id:'c05',track:'common',phase:2,title:'需求拆解与技术方案',duration:'90 MIN',level:'进阶',tags:['设计','评审'],summary:'把模糊目标转化为边界清晰、可验证的工程任务。',goals:['识别需求与约束','绘制系统接口图','制定验证标准'],tasks:['拆解一个机器人功能','输出接口与风险清单','参与方案评审'],deliverable:'模块技术方案书'},
  {id:'c06',track:'common',phase:3,title:'项目复盘与技术表达',duration:'90 MIN',level:'进阶',tags:['复盘','分享'],summary:'沉淀决策、失败与改进，让项目经验可以被团队复用。',goals:['组织技术复盘','撰写高质量文档','进行清晰技术分享'],tasks:['整理问题时间线','完成复盘报告','进行 10 分钟分享'],deliverable:'一篇公开技术复盘'},

  {id:'e01',track:'embedded',phase:1,title:'MCU 与外设入门',duration:'3 HOURS',level:'基础',tags:['MCU','GPIO'],summary:'理解微控制器最小系统，完成 GPIO、定时器与中断实验。',goals:['理解 MCU 启动流程','配置常用外设','掌握中断设计原则'],tasks:['点亮状态灯','实现非阻塞定时任务','测量中断响应'],deliverable:'外设实验固件'},
  {id:'e02',track:'embedded',phase:1,title:'通信总线实战',duration:'4 HOURS',level:'基础',tags:['CAN','UART','SPI'],summary:'掌握机器人节点间常用通信协议与可靠性设计。',goals:['读懂总线时序','设计消息协议','处理丢包与超时'],tasks:['完成 CAN 收发','设计一组消息帧','注入并恢复通信故障'],deliverable:'可靠通信驱动'},
  {id:'e03',track:'embedded',phase:2,title:'Zephyr RTOS 任务设计',duration:'5 HOURS',level:'进阶',tags:['Zephyr','RTOS'],summary:'使用线程、队列和定时器构建可预测的实时应用。',goals:['理解调度与优先级','选择线程通信机制','分析实时性风险'],tasks:['创建多线程应用','实现消息队列','测量任务抖动'],deliverable:'多线程控制程序'},
  {id:'e04',track:'embedded',phase:2,title:'电机驱动与 PID 控制',duration:'6 HOURS',level:'进阶',tags:['PID','Motor'],summary:'从反馈信号到闭环控制，让电机稳定跟随目标。',goals:['建立电机简化模型','实现离散 PID','完成参数整定'],tasks:['采集阶跃响应','实现速度环','完成抗积分饱和'],deliverable:'电机闭环演示'},
  {id:'e05',track:'embedded',phase:3,title:'状态估计与 LQR',duration:'8 HOURS',level:'挑战',tags:['LQR','Estimator'],summary:'面向轮腿等复杂系统，建立状态空间与反馈控制方法。',goals:['理解状态空间模型','实现基础状态估计','完成 LQR 仿真与实机验证'],tasks:['建立简化模型','运行闭环仿真','完成实机参数验证'],deliverable:'稳定运行的控制模块'},
  {id:'e06',track:'embedded',phase:3,title:'实时系统可靠性',duration:'5 HOURS',level:'挑战',tags:['Watchdog','Testing'],summary:'设计监控、降级与故障恢复机制，提升系统赛场可靠性。',goals:['进行故障模式分析','设计看门狗与心跳','构建自动化固件测试'],tasks:['制作 FMEA 表','注入三类故障','实现安全降级'],deliverable:'系统可靠性报告'},

  {id:'v01',track:'vision',phase:1,title:'Python 与图像基础',duration:'3 HOURS',level:'基础',tags:['Python','OpenCV'],summary:'理解图像表示、颜色空间与基础处理算子。',goals:['熟悉 NumPy 图像操作','掌握滤波与二值化','理解坐标与变换'],tasks:['实现颜色分割','对比滤波效果','制作处理流水线'],deliverable:'基础图像处理 Demo'},
  {id:'v02',track:'vision',phase:1,title:'相机模型与标定',duration:'4 HOURS',level:'基础',tags:['Camera','Calibration'],summary:'从成像模型到内外参，建立可靠的视觉测量基础。',goals:['理解针孔相机模型','完成单目标定','评估重投影误差'],tasks:['采集标定数据','求解相机内参','编写误差报告'],deliverable:'相机标定文件与报告'},
  {id:'v03',track:'vision',phase:2,title:'目标检测与装甲板识别',duration:'6 HOURS',level:'进阶',tags:['Detection','PnP'],summary:'构建从候选区域、匹配到位姿估计的完整识别链路。',goals:['设计鲁棒特征','实现目标匹配','使用 PnP 求解位姿'],tasks:['构建样本集','实现识别管线','测量精度与延迟'],deliverable:'可运行的识别模块'},
  {id:'v04',track:'vision',phase:2,title:'ROS 2 与传感器融合',duration:'6 HOURS',level:'进阶',tags:['ROS2','Fusion'],summary:'组织传感器数据流，建立时间、坐标系与融合意识。',goals:['掌握节点与话题','正确管理 TF','同步多源数据'],tasks:['发布传感器话题','构建 TF 树','完成时间同步实验'],deliverable:'传感器融合数据管线'},
  {id:'v05',track:'vision',phase:3,title:'定位、建图与导航',duration:'10 HOURS',level:'挑战',tags:['SLAM','Navigation'],summary:'让移动机器人理解环境，并自主规划安全路径。',goals:['理解里程计与 SLAM','配置代价地图','调试全局和局部规划'],tasks:['构建测试地图','完成定点导航','分析一次定位丢失'],deliverable:'自主导航演示'},
  {id:'v06',track:'vision',phase:3,title:'预测与自瞄系统集成',duration:'8 HOURS',level:'挑战',tags:['Prediction','AutoAim'],summary:'把识别、坐标变换、运动预测与弹道补偿连成实时系统。',goals:['建立延迟模型','实现运动预测','完成端到端性能分析'],tasks:['测量全链路延迟','实现基础预测器','完成动态目标测试'],deliverable:'自瞄系统性能报告'},

  {id:'m01',track:'mechanical',phase:1,title:'机械制图与 CAD',duration:'4 HOURS',level:'基础',tags:['CAD','Drawing'],summary:'掌握参数化建模、装配关系与规范工程图表达。',goals:['建立设计意图','正确使用配合','输出可制造图纸'],tasks:['完成标准件建模','搭建简单装配体','输出二维工程图'],deliverable:'规范装配模型'},
  {id:'m02',track:'mechanical',phase:1,title:'材料、工艺与公差',duration:'3 HOURS',level:'基础',tags:['Material','Tolerance'],summary:'在重量、强度、成本与加工能力之间做工程权衡。',goals:['选择常用材料','理解加工约束','建立公差意识'],tasks:['对比材料方案','设计轴孔配合','审查可制造性'],deliverable:'零件工艺卡'},
  {id:'m03',track:'mechanical',phase:2,title:'机器人结构设计',duration:'7 HOURS',level:'进阶',tags:['Structure','CAD'],summary:'围绕受力、维护与布线设计可靠、轻量的机器人结构。',goals:['建立载荷路径','进行模块化设计','兼顾装配与维护'],tasks:['定义结构接口','完成关键模块设计','参加设计评审'],deliverable:'可评审的结构方案'},
  {id:'m04',track:'mechanical',phase:2,title:'PCB 原理图与布局',duration:'8 HOURS',level:'进阶',tags:['PCB','KiCad'],summary:'从接口定义到布线检查，完成一块可生产的功能板。',goals:['绘制规范原理图','掌握布局布线基础','完成设计规则检查'],tasks:['设计接口电路','完成两层板布局','输出生产文件'],deliverable:'可生产 PCB 工程'},
  {id:'m05',track:'mechanical',phase:3,title:'有限元与轻量化验证',duration:'6 HOURS',level:'挑战',tags:['FEA','Optimize'],summary:'用仿真辅助判断薄弱环节，并通过实验校核模型。',goals:['正确设置边界条件','读懂应力与位移','避免常见仿真假象'],tasks:['完成静力分析','提出轻量化方案','设计验证实验'],deliverable:'结构分析报告'},
  {id:'m06',track:'mechanical',phase:3,title:'整机集成与可靠性测试',duration:'8 HOURS',level:'挑战',tags:['Integration','Test'],summary:'完成装配、线束、维护与耐久性验证，交付可比赛的整机。',goals:['管理机械电气接口','设计测试矩阵','闭环处理失效问题'],tasks:['执行整机检查','完成耐久测试','跟踪问题至关闭'],deliverable:'整机验收报告'}
];
